theme_advanced_toolbar_location: top
theme_advanced_disable: styleselect
theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,justifyleft,justifycenter,justifyright,justifyfull,separator,bullist,numlist,separator,hr,sub,sup,charmap,separator,link,unlink,anchor,image,separator,formatselect,help"
theme_advanced_buttons2: "cut,copy,paste,separator,undo,redo,separator,newdocument,cleanup,removeformat,visualaid,code,separator,forecolor,backcolor,fontselect,fontsizeselect"

